### ISSUE TITLE
Flag()TypeError: undefined is not an object (evaluating 'String.fromCodePoint.apply')

### ISSUE THREAD

**Issue by StefanoCremona** [meeDamian/country-emoji#1]
Hi, there.
I've just tried to display a flag in my react native app and it doesn't work.

I've created from scratch a new project and that is the code I've used:

```
    <View style={styles.container}>
        <Text style={styles.welcome}>
          Welcome to React Native! {flag('CL')}
        </Text>
        <Text style={styles.instructions}>
          To get started, edit App.js
        </Text>
        <Text style={styles.instructions}>
          {instructions}
        </Text>
      </View>
```

Thank you

![flagerror](https://user-images.githubusercontent.com/12048577/32385077-e45744a8-c0b4-11e7-915b-25466d009a56.png)

**Comment by sqow** [comment]
@StefanoCremona Doubtful this is helpful given the age of the issue, but a workaround:
Add the polyfill from https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/fromCodePoint to your `index.android.js` and `index.ios.js` files.

Maybe it'll help someone else.
