### ISSUE TITLE
Add 'Czechia'

### ISSUE THREAD

**Issue by martijnrondeel** [meeDamian/country-emoji#11]
`Czechia` is the [official shortened name](https://en.wikipedia.org/wiki/Name_of_the_Czech_Republic#Adoption_of_Czechia) for the Czech Republic, but it does not appear in the `countries.json` file.

**Comment by meeDamian** [comment]
Addressed in https://github.com/meeDamian/country-emoji/commit/80ef1345e7562c8b57d2d08a20d518c97b74e9a3 :).

Available since `v1.4.2`.
