### ISSUE TITLE
Swift library to handle emoji flags

### ISSUE THREAD

**Issue by BubiDevs** [meeDamian/country-emoji#16]
Hi @meeDamian !

Thanks for sharing the very useful JS library!

I've just created a library called [SwiftFlags](https://github.com/BubiDevs/SwiftFlags), the basically recreate your amazing library in Swift.

I added your repo in the credits, hope that you like it!

Bye!

**Comment by meeDamian** [comment]
Thank you 🙌🏻.

[Added](https://github.com/meeDamian/country-emoji/commit/0bca85e8a628e4cf609222a6ea499e595e84ffc5) reference back to README.

✌🏻

**Comment by BubiDevs** [comment]
Really appreciated! Many thanks! 🙋‍♂️
