### ISSUE TITLE
Types not showing up on NPM

### ISSUE THREAD

**Issue by bscaspar** [meeDamian/country-emoji#23]
It looks like typescript was literally just published, which is amazing, thank you for the work on that!

However they don't appear to show up in the latest NPM package (unless I'm missing something). v1.5.5. Here's what I see in my `node_modules` folder: 

<img width="162" alt="Screen Shot 2021-03-08 at 5 22 30 PM" src="https://user-images.githubusercontent.com/6042704/110399318-e003d600-8032-11eb-87f5-6d66e4e3f0c2.png">

**Comment by ImRodry** [comment]
Can confirm this on my end. I believe there was some issue on Damian's side when making the release since GitHub doesn't pick it up as the latest release and it doesn't look normal, just my guess tho

**Comment by ImRodry** [comment]
I have published the types for this package to @types/country-emoji. Please install them using npm i —save-dev @types/country-emoji until this issue is resolved @bscaspar :)

**Comment by meeDamian** [comment]
Ah. I've forgotten to mark the types file to be included in npm upload.

**Comment by meeDamian** [comment]
Could you verify it works for you now?

```sh
$ npm i country-emoji@1.5.6 && ls -la ./node_modules/country-emoji/index.d.ts

added 1 package, and audited 2 packages in 2s

found 0 vulnerabilities
-rw-r--r--  1 mee  wheel  988 Oct 26  1985 ./node_modules/country-emoji/index.d.ts
```

**Comment by ImRodry** [comment]
I just updated the package normally and it didn't generate any errors so I believe this works!
![image](https://user-images.githubusercontent.com/38259440/111911642-4c80cb00-8a5e-11eb-948f-de0ef7ba8f94.png)
