### ISSUE TITLE
Find a workaround to display country flags on Windows

### ISSUE THREAD

**Issue by pyrytakala** [meeDamian/country-emoji#24]
Country flags don't display as flags on Windows. This breaks the looks of a website using flags quite badly.

This seems to be for political reasons, see e.g. https://answers.microsoft.com/en-us/windows/forum/all/flag-emoji/85b163bc-786a-4918-9042-763ccf4b6c05?page=1

It would be great to have a workaround. Here are some potential solutions: https://stackoverflow.com/questions/54519758/flag-emojis-not-rendering/54663926

**Comment by meeDamian** [comment]
This is quite far beyond the scope of this library.  As it's intended to merely translate between country names, codes, and Unicode flags.  It seems like to support Windows's odd approach, I'd have to decide on a specific graphic style of flags, download and bundle in a ton of PNGs, ensure they're in a public domain, or their license allows for this usage, then maintain and keep up to date as things change over time, and I don't even have a Windows machine to test it on.

Sorry, but this is too much overhead.

**Comment by pyrytakala** [comment]
Ok. 

In case someone else ends up having the same problem, here's a workaround: https://stackoverflow.com/questions/54519758/flag-emojis-not-rendering/67633661#67633661

Can be used like this with country-emoji: `flagemojiToPNG(flag(country))`
