### ISSUE TITLE
The lib is lacking support of some codes of Dutch and French overseas territories and South Sudan

### ISSUE THREAD

**Issue by rverbytskyi** [meeDamian/country-emoji#25]
Currently, the lib does not support the following codes:

- CW - Curaçao, 🇨🇼
- BQ - Caribbean Netherlands, 🇧🇶
- SX - Sint Maarten, 🇸🇽
- SS - South Sudan, 🇸🇸
- BL - Saint Barthélemy, 🇧🇱
- MF - Saint Martin, 🇲🇫

**Comment by meeDamian** [comment]
Merged.

**Comment by BrodaNoel** [comment]
@meeDamian I don't see this in "country-emoji": "^1.5.6",
