### ISSUE TITLE
county-emoji port on python

### ISSUE THREAD

**Issue by Nnonexistent** [meeDamian/country-emoji#40]
Thanks for the library.

I've just ported it to python and published as a [package](https://pypi.org/project/country-emoji/) on PYPI.

I hope you can add it to the list of ports.

Repo: https://github.com/Nnonexistent/country-emoji
Package: https://pypi.org/project/country-emoji/

Best regards, 
Nik

**Comment by meeDamian** [comment]
Thank you, and sorry for delay 😬. Added in https://github.com/meeDamian/country-emoji/commit/9651c9dba071afe61526dd3e2c4875840fef3124 (merge to master soon)
