### ISSUE TITLE
Missing new name for Turkey

### ISSUE THREAD

**Issue by BrodaNoel** [meeDamian/country-emoji#44]
Turkey is now called `Türkiye`

India is also changing the name, so, we have to add them

**Comment by meeDamian** [comment]
Done in https://github.com/meeDamian/country-emoji/commit/ebcd665af96a443cbc5e4b7274b2cf77c35442c8#diff-dbe223024e02eb094cae1f8e7dd33a4df7034af678f52767bd57cd0cc7c16ed5L228
